### ISSUE TITLE
Sorting is a little wonky

### ISSUE THREAD

**Issue by GregariousJB** [mcglonelevi/RaftModSortInventory#4]
Video: https://streamable.com/wpdtgj

I'm assuming it's alphabetical, but there's several items that don't want to be sorted as such. And one item - **M**etal Ingot - that's OK with being sorted before and after **N**ails.

There's also the Bee Jar, which should be sorted at the beginning, but perhaps it's a brand new item and hasn't been added to the code yet. I haven't taken a look at the code: 

![image](https://i.imgur.com/1L3MznO.png)

In any case, thank you for this mod. I like staying organized.

EDIT: This is also happening with **G**iant Clams: https://streamable.com/ssmhev

**Comment by dcsobral** [comment]
Sorting uses the game's internal name for the item. That obviously differs from the localized name -- perhaps sorting should be done by the localized name?

**Comment by mcglonelevi** [comment]
I believe this is fixed in #6.  Please see made-by-traxam's fork.
