### ISSUE TITLE
Possibility of changing the key

### ISSUE THREAD

**Issue by Henonnnn** [mcglonelevi/RaftModSortInventory#7]
Hey I'm french so I have an AZERTY keyboard that make my "z" key the key for move forward is it possible to make a thing that allows you to change the keybind please ?

**Comment by mcglonelevi** [comment]
Hey @Henonnnn,

I haven't played Raft in years.  @made-by-traxam maintains a more up-to-date fork here:

https://github.com/made-by-traxam/RaftModSortInventory

You may want to create an issue there.  If you have VisualStudio and have the ability to compile it yourself, you could change the keybind on this line:

https://github.com/made-by-traxam/RaftModSortInventory/blob/cfe4026881535912c27dbeffeaba67d9fb4a1df4/SortInventory/SortInventoryMod.cs#L16

Hope this helps!
